// 引诗为名 · 古籍诗词名字卡片库
// 涵盖诗经、楚辞、唐诗、宋词、四书、道经易、尚书礼记等
// 每张卡片含：引文 / 原文 / 释义 / 寓意 / 字解 / 性别 / 标签

import type { NameCard } from "./types";

export const NAME_CARDS: NameCard[] = [
  // ==================== 诗经（22） ====================
  {
    id: "sj-zhuohua",
    name: "灼华",
    chars: [
      { char: "灼", meaning: "鲜明、繁盛，如火之盛" },
      { char: "华", meaning: "花，亦指光彩、繁华" },
    ],
    category: "shijing",
    source: "《诗经·周南·桃夭》",
    dynasty: "西周",
    author: "佚名",
    citation: "桃之夭夭，灼灼其华。",
    originalText:
      "桃之夭夭，灼灼其华。之子于归，宜其室家。桃之夭夭，有蕡其实。之子于归，宜其家室。",
    interpretation:
      "桃树繁茂，花儿开得鲜明灿烂。这位姑娘出嫁，定能使家庭和睦美满。",
    meaning:
      "取桃花明艳之姿，寓意容颜秀美、光彩照人，又含宜室宜家、美满和顺之福。",
    gender: "female",
    tags: ["明艳", "吉祥", "婚姻美满"],
  },
  {
    id: "sj-zhenzhen",
    name: "蓁蓁",
    chars: [
      { char: "蓁", meaning: "草木繁盛貌" },
    ],
    category: "shijing",
    source: "《诗经·周南·桃夭》",
    dynasty: "西周",
    author: "佚名",
    citation: "桃之夭夭，其叶蓁蓁。",
    originalText: "桃之夭夭，其叶蓁蓁。之子于归，宜其家人。",
    interpretation: "桃树幼嫩，叶子茂密葱郁。这位姑娘出嫁，全家皆得和睦。",
    meaning: "草木繁盛之貌，寓意生机勃勃、家族兴旺、福泽绵长。",
    gender: "female",
    tags: ["繁盛", "生机", "兴旺"],
  },
  {
    id: "sj-wanqing",
    name: "婉清",
    chars: [
      { char: "婉", meaning: "柔美、和顺" },
      { char: "清", meaning: "清明、纯洁" },
    ],
    category: "shijing",
    source: "《诗经·郑风·野有蔓草》",
    dynasty: "西周",
    author: "佚名",
    citation: "有美一人，婉如清扬。",
    originalText:
      "野有蔓草，零露漙兮。有美一人，清扬婉兮。邂逅相遇，适我愿兮。",
    interpretation: "荒野蔓草之上露珠滚动，有位美人眉目清明婉丽，偶然相遇正合我心。",
    meaning: "化「婉如清扬」为婉清，寓眉目清秀、温婉纯洁，气质如露般澄澈。",
    gender: "female",
    tags: ["温婉", "清丽", "邂逅"],
  },
  {
    id: "sj-youning",
    name: "攸宁",
    chars: [
      { char: "攸", meaning: "所、乃；安闲" },
      { char: "宁", meaning: "安宁、平静" },
    ],
    category: "shijing",
    source: "《诗经·小雅·斯干》",
    dynasty: "西周",
    author: "佚名",
    citation: "君子攸宁。",
    originalText: "如跂斯翼，如矢斯棘，如鸟斯革，如翚斯飞，君子攸芋。君子攸宁。",
    interpretation: "宫室如鸟展翅、如雉飞扬般华美，是君子安居之所、安息之地。",
    meaning: "君子安居之所，寓一生安泰宁和、居有定所、心有所归。",
    gender: "unisex",
    tags: ["安宁", "安居", "君子"],
  },
  {
    id: "sj-huiyin",
    name: "徽音",
    chars: [
      { char: "徽", meaning: "美好、美德" },
      { char: "音", meaning: "声誉、名声" },
    ],
    category: "shijing",
    source: "《诗经·大雅·思齐》",
    dynasty: "西周",
    author: "佚名",
    citation: "大姒嗣徽音，则百斯男。",
    originalText: "思齐大任，文王之母，思媚周姜，京室之妇。大姒嗣徽音，则百斯男。",
    interpretation: "太姒继承太姜太任的美德美名，故能子孙众多、家道兴旺。",
    meaning: "美誉德音，寓承继美德、声名远播、德行流芳。",
    gender: "female",
    tags: ["美德", "美誉", "传承"],
  },
  {
    id: "sj-siqi",
    name: "思齐",
    chars: [
      { char: "思", meaning: "语助词，亦含思念、思齐见贤之意" },
      { char: "齐", meaning: "端庄、庄敬；齐贤" },
    ],
    category: "shijing",
    source: "《诗经·大雅·思齐》",
    dynasty: "西周",
    author: "佚名",
    citation: "思齐大任，文王之母。",
    originalText: "思齐大任，文王之母，思媚周姜，京室之妇。",
    interpretation: "端庄庄敬的太任，是文王的母亲，和顺周姜，是王室之妇。",
    meaning: "庄敬贤淑，亦含见贤思齐之意，寓品德端庄、向善修德。",
    gender: "female",
    tags: ["端庄", "贤淑", "见贤思齐"],
  },
  {
    id: "sj-jingjia",
    name: "静嘉",
    chars: [
      { char: "静", meaning: "洁净、宁静" },
      { char: "嘉", meaning: "美好、善" },
    ],
    category: "shijing",
    source: "《诗经·大雅·既醉》",
    dynasty: "西周",
    author: "佚名",
    citation: "其告维何？笾豆静嘉。",
    originalText: "其告维何？笾豆静嘉。朋友攸摄，摄以威仪。",
    interpretation: "祝告之辞何所说？祭器笾豆洁净美好，朋友助祭皆端庄有仪。",
    meaning: "洁净美好，寓心境清明、品性温良、举止有度。",
    gender: "unisex",
    tags: ["洁净", "美好", "温良"],
  },
  {
    id: "sj-muqing",
    name: "穆清",
    chars: [
      { char: "穆", meaning: "和美、肃敬" },
      { char: "清", meaning: "清明、清和" },
    ],
    category: "shijing",
    source: "《诗经·大雅·烝民》",
    dynasty: "西周",
    author: "尹吉甫",
    citation: "吉甫作诵，穆如清风。",
    originalText: "吉甫作诵，穆如清风。仲山甫永怀，以慰其心。",
    interpretation: "吉甫作此颂诗，和美如清风拂面，以慰仲山甫深长之思。",
    meaning: "和美清和如风，寓性情温润、令人如沐春风、德化远人。",
    gender: "male",
    tags: ["和美", "温润", "德化"],
  },
  {
    id: "sj-roujia",
    name: "柔嘉",
    chars: [
      { char: "柔", meaning: "温和、柔顺" },
      { char: "嘉", meaning: "美好、善" },
    ],
    category: "shijing",
    source: "《诗经·大雅·烝民》",
    dynasty: "西周",
    author: "尹吉甫",
    citation: "仲山甫之德，柔嘉维则。",
    originalText: "人亦有言，柔则茹之，刚则吐之。仲山甫之德，柔嘉维则。",
    interpretation: "俗语说软的就吃、硬的就吐，而仲山甫之德，温柔和美才是准则。",
    meaning: "温柔和美为德之准则，寓性情温良、宽厚有德、可大可久。",
    gender: "female",
    tags: ["温柔", "美德", "宽厚"],
  },
  {
    id: "sj-jingxing",
    name: "景行",
    chars: [
      { char: "景", meaning: "大、光明；景仰" },
      { char: "行", meaning: "道路、德行" },
    ],
    category: "shijing",
    source: "《诗经·小雅·车舝》",
    dynasty: "西周",
    author: "佚名",
    citation: "高山仰止，景行行止。",
    originalText: "陟彼高冈，析其柞薪。高山仰止，景行行止。",
    interpretation: "登彼高冈劈柴薪，见高山则仰望，见大道则行之。",
    meaning: "光明大道令人景仰而行，寓志向高远、行止有度、追慕圣贤。",
    gender: "male",
    tags: ["高远", "景仰", "德行"],
  },
  {
    id: "sj-weizhen",
    name: "维桢",
    chars: [
      { char: "维", meaning: "是、乃；维系" },
      { char: "桢", meaning: "筑墙两端的木柱，喻栋梁" },
    ],
    category: "shijing",
    source: "《诗经·大雅·文王》",
    dynasty: "西周",
    author: "佚名",
    citation: "王国克生，维周之桢。",
    originalText: "王国克生，维周之桢；济济多士，文王以宁。",
    interpretation: "王国所生之贤才，是周室的栋梁；济济多士，文王赖以安宁。",
    meaning: "国之栋梁，寓才堪大用、家国柱石、稳重可靠。",
    gender: "male",
    tags: ["栋梁", "贤才", "稳重"],
  },
  {
    id: "sj-bangyan",
    name: "邦彦",
    chars: [
      { char: "邦", meaning: "国、邦国" },
      { char: "彦", meaning: "美士、才德之人" },
    ],
    category: "shijing",
    source: "《诗经·郑风·羔裘》",
    dynasty: "西周",
    author: "佚名",
    citation: "彼其之子，邦之彦兮。",
    originalText: "羔裘豹饰，孔武有力。彼其之子，邦之彦兮。",
    interpretation: "身着羔裘豹饰，威武有力，那人正是邦国之美士啊。",
    meaning: "邦国之英才，寓才德兼美、为国之器、卓尔不群。",
    gender: "male",
    tags: ["英才", "邦国", "才德"],
  },
  {
    id: "sj-jingshu",
    name: "静姝",
    chars: [
      { char: "静", meaning: "娴静、贞静" },
      { char: "姝", meaning: "美好" },
    ],
    category: "shijing",
    source: "《诗经·邶风·静女》",
    dynasty: "西周",
    author: "佚名",
    citation: "静女其姝，俟我于城隅。",
    originalText: "静女其姝，俟我于城隅。爱而不见，搔首踟蹰。",
    interpretation: "娴静的姑娘真美丽，在城角等我；藏起来看不见，急得我搔首徘徊。",
    meaning: "娴静美好，寓性情贞静、容貌清丽、惹人怜爱。",
    gender: "female",
    tags: ["娴静", "美丽", "贞洁"],
  },
  {
    id: "sj-xunmei",
    name: "洵美",
    chars: [
      { char: "洵", meaning: "实在、诚然" },
      { char: "美", meaning: "美好" },
    ],
    category: "shijing",
    source: "《诗经·邶风·静女》",
    dynasty: "西周",
    author: "佚名",
    citation: "自牧归荑，洵美且异。",
    originalText: "自牧归荑，洵美且异。匪女之为美，美人之贻。",
    interpretation: "从郊野赠我白茅芽，实在美丽又奇异；并非草儿本身美，是美人之赠啊。",
    meaning: "诚然美好，寓美而真实、卓尔不凡、情意深长。",
    gender: "female",
    tags: ["美好", "真挚", "情谊"],
  },
  {
    id: "sj-ruying",
    name: "如英",
    chars: [
      { char: "如", meaning: "如同、好像" },
      { char: "英", meaning: "花、英才" },
    ],
    category: "shijing",
    source: "《诗经·魏风·汾沮洳》",
    dynasty: "西周",
    author: "佚名",
    citation: "彼其之子，美如英。",
    originalText: "彼其之子，美如英。美如英，殊异乎公行。",
    interpretation: "那人啊，美得像花朵一般，与公行截然不同。",
    meaning: "美如花朵，亦喻英华出众，寓容貌才情俱佳、超群绝伦。",
    gender: "female",
    tags: ["美丽", "英华", "出众"],
  },
  {
    id: "sj-kaifeng",
    name: "凯风",
    chars: [
      { char: "凯", meaning: "和暖、胜利" },
      { char: "风", meaning: "风、风化" },
    ],
    category: "shijing",
    source: "《诗经·邶风·凯风》",
    dynasty: "西周",
    author: "佚名",
    citation: "凯风自南，吹彼棘心。",
    originalText: "凯风自南，吹彼棘心。棘心夭夭，母氏劬劳。",
    interpretation: "和暖的南风从南吹来，吹拂那酸枣的嫩心；嫩心柔弱，母亲操劳养育。",
    meaning: "和暖南风喻母爱，寓感恩反哺、温和向善、家道和乐。",
    gender: "male",
    tags: ["和暖", "感恩", "母爱"],
  },
  {
    id: "sj-wenyin",
    name: "文茵",
    chars: [
      { char: "文", meaning: "华美、文采" },
      { char: "茵", meaning: "车中虎皮坐垫，亦指如茵" },
    ],
    category: "shijing",
    source: "《诗经·秦风·小戎》",
    dynasty: "西周",
    author: "佚名",
    citation: "文茵畅毂，驾我骐馵。",
    originalText: "小戎俴收，五楘梁辀。游环胁驱，阴靷鋈续。文茵畅毂，驾我骐馵。",
    interpretation: "虎皮花纹的车垫，长长的车毂，驾起我的骐马与馵马。",
    meaning: "华美如茵，寓文采斐然、安稳从容、气度不凡。",
    gender: "female",
    tags: ["华美", "从容", "文采"],
  },
  {
    id: "sj-qionghua",
    name: "琼华",
    chars: [
      { char: "琼", meaning: "美玉" },
      { char: "华", meaning: "花、光彩" },
    ],
    category: "shijing",
    source: "《诗经·齐风·著》",
    dynasty: "西周",
    author: "佚名",
    citation: "尚之以琼华乎而。",
    originalText: "俟我于著乎而，充耳以素乎而，尚之以琼华乎而。",
    interpretation: "他在门屏间等我，以白丝系充耳，再以美玉花点缀其上。",
    meaning: "美玉之华彩，寓品性如玉、光彩照人、高洁华贵。",
    gender: "female",
    tags: ["美玉", "高洁", "华贵"],
  },
  {
    id: "sj-hanfei",
    name: "翰飞",
    chars: [
      { char: "翰", meaning: "高飞、羽翼；文辞" },
      { char: "飞", meaning: "飞翔" },
    ],
    category: "shijing",
    source: "《诗经·小雅·小宛》",
    dynasty: "西周",
    author: "佚名",
    citation: "宛彼鸣鸠，翰飞戾天。",
    originalText: "宛彼鸣鸠，翰飞戾天。我心忧伤，念昔先人。",
    interpretation: "小小的斑鸠鸣叫着，高飞直上云天；我心忧伤，思念先人。",
    meaning: "高飞戾天，寓志向高远、振翅有为、文采飞扬。",
    gender: "male",
    tags: ["高飞", "志向", "文采"],
  },
  {
    id: "sj-ruxue",
    name: "如雪",
    chars: [
      { char: "如", meaning: "如同" },
      { char: "雪", meaning: "雪，喻洁白" },
    ],
    category: "shijing",
    source: "《诗经·曹风·蜉蝣》",
    dynasty: "西周",
    author: "佚名",
    citation: "蜉蝣掘阅，麻衣如雪。",
    originalText: "蜉蝣掘阅，麻衣如雪。心之忧矣，于我归说。",
    interpretation: "蜉蝣破穴而出，麻衣洁白如雪；我心忧伤，何处是我的归宿。",
    meaning: "洁白如雪，寓心地纯洁、纤尘不染、清雅出尘。",
    gender: "female",
    tags: ["纯洁", "洁白", "清雅"],
  },
  {
    id: "sj-jiahuì",
    name: "嘉卉",
    chars: [
      { char: "嘉", meaning: "美好" },
      { char: "卉", meaning: "草木之总称" },
    ],
    category: "shijing",
    source: "《诗经·小雅·四月》",
    dynasty: "西周",
    author: "佚名",
    citation: "山有嘉卉，侯栗侯梅。",
    originalText: "山有嘉卉，侯栗侯梅。废为残贼，莫知其尤。",
    interpretation: "山上有美好的草木，有栗树有梅树；却被残害砍伐，无人知其过错。",
    meaning: "美好的草木，寓品性芳洁、如花木之秀、宜其生机。",
    gender: "female",
    tags: ["芳洁", "生机", "美好"],
  },
  {
    id: "sj-xinning",
    name: "馨宁",
    chars: [
      { char: "馨", meaning: "芳香远闻" },
      { char: "宁", meaning: "安宁" },
    ],
    category: "shijing",
    source: "《诗经·周颂·载芟》",
    dynasty: "西周",
    author: "佚名",
    citation: "有椒其馨，胡考之宁。",
    originalText: "有椒其馨，胡考之宁。匪且有且，匪今斯今，振古如兹。",
    interpretation: "花椒香气远播，老人长寿安宁；不只是今天如此，自古皆然。",
    meaning: "馨香安宁，寓德香远播、福寿康宁、家道长久。",
    gender: "unisex",
    tags: ["馨香", "安宁", "福寿"],
  },

  // ==================== 楚辞（12） ====================
  {
    id: "cc-lingjun",
    name: "灵均",
    chars: [
      { char: "灵", meaning: "神灵、善、灵秀" },
      { char: "均", meaning: "平、公平；屈原之字" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "名余曰正则兮，字余曰灵均。",
    originalText:
      "皇览揆余初度兮，肇锡余以嘉名。名余曰正则兮，字余曰灵均。",
    interpretation: "父亲考察我初生时的气度，赐我美名：名为正则，字为灵均。",
    meaning: "屈原之字，寓灵秀中正、才德均平、不群于世。",
    gender: "male",
    tags: ["灵秀", "中正", "屈子"],
  },
  {
    id: "cc-zhengze",
    name: "正则",
    chars: [
      { char: "正", meaning: "端正、正直" },
      { char: "则", meaning: "法则、准则" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "名余曰正则兮，字余曰灵均。",
    originalText: "皇览揆余初度兮，肇锡余以嘉名。名余曰正则兮，字余曰灵均。",
    interpretation: "父亲赐我美名：名为正则，意为端正合于法则。",
    meaning: "端正合则，寓品行端正、守正不阿、为世法则。",
    gender: "male",
    tags: ["端正", "守正", "法则"],
  },
  {
    id: "cc-jiaming",
    name: "嘉名",
    chars: [
      { char: "嘉", meaning: "美好" },
      { char: "名", meaning: "名声、名字" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "肇锡余以嘉名。",
    originalText: "皇览揆余初度兮，肇锡余以嘉名。",
    interpretation: "父亲考察我初生的气度，开始赐予我美好的名字。",
    meaning: "美好之名，寓声名美善、不负所期、流芳可久。",
    gender: "unisex",
    tags: ["美名", "声名", "美善"],
  },
  {
    id: "cc-xinfang",
    name: "信芳",
    chars: [
      { char: "信", meaning: "确实、诚信" },
      { char: "芳", meaning: "芳香、美德" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "不吾知其亦已兮，苟余情其信芳。",
    originalText: "不吾知其亦已兮，苟余情其信芳。芳与泽其杂糅兮，唯昭质其犹未亏。",
    interpretation: "无人了解我也就罢了，只要我的情志确实芳洁；芳香与污泽纵然杂糅，我清明的本质仍未亏损。",
    meaning: "情志确实芳洁，寓坚守本心、德行芬芳、不随流俗。",
    gender: "female",
    tags: ["芳洁", "坚守", "本心"],
  },
  {
    id: "cc-huaijin",
    name: "怀瑾",
    chars: [
      { char: "怀", meaning: "怀藏、胸怀" },
      { char: "瑾", meaning: "美玉" },
    ],
    category: "chuci",
    source: "《楚辞·九章·怀沙》",
    dynasty: "战国",
    author: "屈原",
    citation: "怀瑾握瑜兮，穷不知所示。",
    originalText: "重华不可迓兮，孰知余之从容。古固有不并兮，岂知其何故。怀瑾握瑜兮，穷不知所示。",
    interpretation: "怀藏美玉手握良璧，却困厄而无人可示。",
    meaning: "胸怀美玉，寓德才内蕴、不炫于外、贞介自守。",
    gender: "male",
    tags: ["美玉", "德才", "自守"],
  },
  {
    id: "cc-wangshu",
    name: "望舒",
    chars: [
      { char: "望", meaning: "迎、企望" },
      { char: "舒", meaning: "舒展、月神驭者" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "前望舒使先驱兮，后飞廉使奔属。",
    originalText: "吾令丰隆乘云兮，求宓妃之所在。解佩纕以结言兮，吾令蹇修以为理。前望舒使先驱兮，后飞廉使奔属。",
    interpretation: "让月神望舒在前面开路，让风神飞廉在后面追随。",
    meaning: "神话中为月驾车之神，寓皎洁如月、从容引路、清辉远照。",
    gender: "unisex",
    tags: ["月神", "皎洁", "清辉"],
  },
  {
    id: "cc-ruohua",
    name: "若华",
    chars: [
      { char: "若", meaning: "若木，神话中日入处之树" },
      { char: "华", meaning: "花、光华" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "折若木以拂日兮，聊逍遥以相羊。",
    originalText: "折若木以拂日兮，聊逍遥以相羊。前望舒使先驱兮，后飞廉使奔属。",
    interpretation: "折下若木的花枝拂拭太阳，姑且逍遥徜徉一番。",
    meaning: "若木之神花，神话中能发出光芒，寓光华照人、神秀不凡、逍遥自在。",
    gender: "female",
    tags: ["神话", "光华", "逍遥"],
  },
  {
    id: "cc-duoruo",
    name: "杜若",
    chars: [
      { char: "杜", meaning: "杜木" },
      { char: "若", meaning: "杜若，香草名" },
    ],
    category: "chuci",
    source: "《楚辞·九歌·湘君》",
    dynasty: "战国",
    author: "屈原",
    citation: "采芳洲兮杜若，将以遗兮下女。",
    originalText: "采芳洲兮杜若，将以遗兮下女。时不可兮再得，聊逍遥兮容与。",
    interpretation: "在芳草之洲采摘杜若香草，想赠予身边的侍女；良辰不可再得，姑且逍遥徘徊。",
    meaning: "香草之名，寓品行芬芳、清雅出尘、待人以诚。",
    gender: "female",
    tags: ["香草", "清雅", "芬芳"],
  },
  {
    id: "cc-xiuneng",
    name: "修能",
    chars: [
      { char: "修", meaning: "修长、美好；修治" },
      { char: "能", meaning: "才能、能力" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "纷吾既有此内美兮，又重之以修能。",
    originalText: "纷吾既有此内美兮，又重之以修能。扈江离与辟芷兮，纫秋兰以为佩。",
    interpretation: "我既已拥有这许多内在美德，又加以修治杰出的才能；身披江离芷草，编秋兰为佩饰。",
    meaning: "修治才干、内外兼美，寓德才并进、自强不息、雅致不俗。",
    gender: "male",
    tags: ["才干", "兼美", "自强"],
  },
  {
    id: "cc-feilong",
    name: "飞龙",
    chars: [
      { char: "飞", meaning: "飞翔" },
      { char: "龙", meaning: "龙" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "驾飞龙兮北征，邅吾道兮洞庭。",
    originalText: "驾飞龙兮北征，邅吾道兮洞庭。薜荔柏兮蕙绸，荪桡兮兰旌。",
    interpretation: "驾着飞龙向北远行，转道经过洞庭；以薜荔为帐蕙草为绸，以荪为桨兰为旗。",
    meaning: "驾龙腾飞，寓气概非凡、腾达有为、志在四方。",
    gender: "male",
    tags: ["腾飞", "气概", "远志"],
  },
  {
    id: "cc-lanzhi",
    name: "兰芷",
    chars: [
      { char: "兰", meaning: "兰草，君子之香" },
      { char: "芷", meaning: "白芷，香草" },
    ],
    category: "chuci",
    source: "《楚辞·离骚》",
    dynasty: "战国",
    author: "屈原",
    citation: "兰芷变而不芳兮，荃蕙化而为茅。",
    originalText: "兰芷变而不芳兮，荃蕙化而为茅。何昔日之芳草兮，今直为此萧艾也。",
    interpretation: "兰草白芷竟变得不再芳香，荃蕙也化成了茅草；昔日芳草，今竟成萧艾。",
    meaning: "兰芷皆香草，喻君子之德，寓品行高洁、芳华自守、不同流俗。",
    gender: "female",
    tags: ["香草", "高洁", "君子"],
  },
  {
    id: "cc-woshu",
    name: "握瑜",
    chars: [
      { char: "握", meaning: "握持" },
      { char: "瑜", meaning: "美玉" },
    ],
    category: "chuci",
    source: "《楚辞·九章·怀沙》",
    dynasty: "战国",
    author: "屈原",
    citation: "怀瑾握瑜兮，穷不知所示。",
    originalText: "怀瑾握瑜兮，穷不知所示。",
    interpretation: "怀揣美玉手握良璧，却困厄而无处展示。",
    meaning: "手握美玉，寓怀才抱德、贞洁自守、不轻易示人。",
    gender: "male",
    tags: ["美玉", "怀才", "自守"],
  },

  // ==================== 唐诗（18） ====================
  {
    id: "ts-haoran",
    name: "浩然",
    chars: [
      { char: "浩", meaning: "盛大、广阔" },
      { char: "然", meaning: "……的样子" },
    ],
    category: "tangshi",
    source: "李白《赠孟浩然》",
    dynasty: "唐",
    author: "李白",
    citation: "吾爱孟浩然，风流天下闻。",
    originalText: "吾爱孟浩然，风流天下闻。红颜弃轩冕，白首卧松云。醉月频中圣，迷花不事君。高山安可仰，徒此揖清芬。",
    interpretation: "我敬爱孟浩然，他风流倜傥天下闻名；少壮时便弃绝功名，白发仍卧于松云之间。",
    meaning: "浩然之气，亦取孟浩然之风流高致，寓胸襟开阔、正气凛然、超然物外。",
    gender: "male",
    tags: ["浩然", "正气", "超然"],
  },
  {
    id: "ts-yunfan",
    name: "云帆",
    chars: [
      { char: "云", meaning: "云、高远" },
      { char: "帆", meaning: "船帆" },
    ],
    category: "tangshi",
    source: "李白《行路难》",
    dynasty: "唐",
    author: "李白",
    citation: "长风破浪会有时，直挂云帆济沧海。",
    originalText:
      "金樽清酒斗十千，玉盘珍羞直万钱。停杯投箸不能食，拔剑四顾心茫然。……长风破浪会有时，直挂云帆济沧海。",
    interpretation: "乘风破浪的时机终会到来，到时高高挂起云帆横渡沧海。",
    meaning: "高挂云帆渡海，寓志向远大、乘风破浪、终达彼岸。",
    gender: "male",
    tags: ["远志", "破浪", "进取"],
  },
  {
    id: "ts-changfeng",
    name: "长风",
    chars: [
      { char: "长", meaning: "长远、强劲" },
      { char: "风", meaning: "风" },
    ],
    category: "tangshi",
    source: "李白《行路难》",
    dynasty: "唐",
    author: "李白",
    citation: "长风破浪会有时，直挂云帆济沧海。",
    originalText: "长风破浪会有时，直挂云帆济沧海。",
    interpretation: "强劲的长风破浪之时终会到来，到时直挂云帆横渡沧海。",
    meaning: "强劲长风，寓气势磅礴、乘势而上、无所畏惧。",
    gender: "male",
    tags: ["气势", "进取", "无畏"],
  },
  {
    id: "ts-zhehui",
    name: "朝晖",
    chars: [
      { char: "朝", meaning: "早晨" },
      { char: "晖", meaning: "阳光、光辉" },
    ],
    category: "tangshi",
    source: "王勃《滕王阁序》",
    dynasty: "唐",
    author: "王勃",
    citation: "潦水尽而寒潭清，烟光凝而暮山紫。……朝晖夕阴，气象万千。",
    originalText:
      "披绣闼，俯雕甍，山原旷其盈视，川泽纡其骇瞩。闾阎扑地，钟鸣鼎食之家；舸舰弥津，青雀黄龙之舳。云销雨霁，彩彻区明。落霞与孤鹜齐飞，秋水共长天一色。",
    interpretation: "雨后潭水清澈，烟光凝聚暮山呈紫；朝有阳光夕有阴，气象变化万千。",
    meaning: "晨之光辉，寓朝气蓬勃、光明灿烂、前程似锦。",
    gender: "male",
    tags: ["朝气", "光明", "灿烂"],
  },
  {
    id: "ts-luoxia",
    name: "落霞",
    chars: [
      { char: "落", meaning: "落下、映落" },
      { char: "霞", meaning: "晚霞" },
    ],
    category: "tangshi",
    source: "王勃《滕王阁序》",
    dynasty: "唐",
    author: "王勃",
    citation: "落霞与孤鹜齐飞，秋水共长天一色。",
    originalText: "落霞与孤鹜齐飞，秋水共长天一色。",
    interpretation: "晚霞与孤雁一同飞翔，秋水与辽阔长天融为一色。",
    meaning: "晚霞映空，寓绚丽多姿、意境开阔、超逸不凡。",
    gender: "female",
    tags: ["绚丽", "开阔", "超逸"],
  },
  {
    id: "ts-qiushui",
    name: "秋水",
    chars: [
      { char: "秋", meaning: "秋天、清澈" },
      { char: "水", meaning: "水" },
    ],
    category: "tangshi",
    source: "王勃《滕王阁序》",
    dynasty: "唐",
    author: "王勃",
    citation: "落霞与孤鹜齐飞，秋水共长天一色。",
    originalText: "落霞与孤鹜齐飞，秋水共长天一色。",
    interpretation: "晚霞与孤雁齐飞，秋天的江水与辽阔天空融为一色。",
    meaning: "秋日江水清澈，寓澄澈明净、目光如水、胸襟开阔。",
    gender: "female",
    tags: ["澄澈", "明净", "开阔"],
  },
  {
    id: "ts-changtian",
    name: "长天",
    chars: [
      { char: "长", meaning: "辽阔、长远" },
      { char: "天", meaning: "天空" },
    ],
    category: "tangshi",
    source: "王勃《滕王阁序》",
    dynasty: "唐",
    author: "王勃",
    citation: "秋水共长天一色。",
    originalText: "落霞与孤鹜齐飞，秋水共长天一色。",
    interpretation: "秋水与辽阔的天空融为同一色。",
    meaning: "辽阔长空，寓胸襟广阔、志存高远、气度恢弘。",
    gender: "male",
    tags: ["辽阔", "高远", "恢弘"],
  },
  {
    id: "ts-chunhui",
    name: "春晖",
    chars: [
      { char: "春", meaning: "春天、生机" },
      { char: "晖", meaning: "阳光、恩辉" },
    ],
    category: "tangshi",
    source: "孟郊《游子吟》",
    dynasty: "唐",
    author: "孟郊",
    citation: "谁言寸草心，报得三春晖。",
    originalText: "慈母手中线，游子身上衣。临行密密缝，意恐迟迟归。谁言寸草心，报得三春晖。",
    interpretation: "谁说小草那点微薄的心意，能报答得了春日阳光般的母恩呢？",
    meaning: "春日阳光喻母恩，寓感恩图报、温暖仁厚、不忘根本。",
    gender: "unisex",
    tags: ["感恩", "温暖", "母恩"],
  },
  {
    id: "ts-qingquan",
    name: "清泉",
    chars: [
      { char: "清", meaning: "清澈" },
      { char: "泉", meaning: "泉水" },
    ],
    category: "tangshi",
    source: "王维《山居秋暝》",
    dynasty: "唐",
    author: "王维",
    citation: "明月松间照，清泉石上流。",
    originalText: "空山新雨后，天气晚来秋。明月松间照，清泉石上流。竹喧归浣女，莲动下渔舟。随意春芳歇，王孙自可留。",
    interpretation: "空山新雨之后，傍晚的秋意清凉；明月照在松间，清泉在石上流淌。",
    meaning: "清澈泉水，寓心境澄明、品行纯洁、淡泊自守。",
    gender: "unisex",
    tags: ["澄明", "纯洁", "淡泊"],
  },
  {
    id: "ts-kongshan",
    name: "空山",
    chars: [
      { char: "空", meaning: "空寂、空灵" },
      { char: "山", meaning: "山" },
    ],
    category: "tangshi",
    source: "王维《山居秋暝》",
    dynasty: "唐",
    author: "王维",
    citation: "空山新雨后，天气晚来秋。",
    originalText: "空山新雨后，天气晚来秋。明月松间照，清泉石上流。",
    interpretation: "空寂的山林新雨之后，傍晚的天气已透出秋意。",
    meaning: "空灵山林，寓心境空灵、超然物外、淡泊宁静。",
    gender: "male",
    tags: ["空灵", "超然", "宁静"],
  },
  {
    id: "ts-jinse",
    name: "锦瑟",
    chars: [
      { char: "锦", meaning: "锦绣、华美" },
      { char: "瑟", meaning: "瑟，弦乐器" },
    ],
    category: "tangshi",
    source: "李商隐《锦瑟》",
    dynasty: "唐",
    author: "李商隐",
    citation: "锦瑟无端五十弦，一弦一柱思华年。",
    originalText: "锦瑟无端五十弦，一弦一柱思华年。庄生晓梦迷蝴蝶，望帝春心托杜鹃。沧海月明珠有泪，蓝田日暖玉生烟。此情可待成追忆，只是当时已惘然。",
    interpretation: "华美的瑟为何竟有五十弦，一弦一柱都惹人追思华年；往事可待追忆，只是当时已惘然。",
    meaning: "华美之瑟，寓情致深婉、才思华美、回味悠长。",
    gender: "female",
    tags: ["华美", "深婉", "才思"],
  },
  {
    id: "ts-ziyan",
    name: "紫烟",
    chars: [
      { char: "紫", meaning: "紫色、祥瑞" },
      { char: "烟", meaning: "烟霞、云气" },
    ],
    category: "tangshi",
    source: "李白《望庐山瀑布》",
    dynasty: "唐",
    author: "李白",
    citation: "日照香炉生紫烟，遥看瀑布挂前川。",
    originalText: "日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。",
    interpretation: "阳光照在香炉峰上生出紫色烟霞，远远望去瀑布如白练挂于山前。",
    meaning: "紫色烟霞，寓祥瑞飘逸、超尘脱俗、气象瑰丽。",
    gender: "female",
    tags: ["祥瑞", "飘逸", "瑰丽"],
  },
  {
    id: "ts-feiliu",
    name: "飞流",
    chars: [
      { char: "飞", meaning: "飞泻、奔腾" },
      { char: "流", meaning: "水流" },
    ],
    category: "tangshi",
    source: "李白《望庐山瀑布》",
    dynasty: "唐",
    author: "李白",
    citation: "飞流直下三千尺，疑是银河落九天。",
    originalText: "日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。",
    interpretation: "飞泻的水流直下三千尺，仿佛是银河从九天倾落。",
    meaning: "飞泻之流，寓气势磅礴、奔放不羁、一往无前。",
    gender: "male",
    tags: ["气势", "奔放", "一往无前"],
  },
  {
    id: "ts-bikong",
    name: "碧空",
    chars: [
      { char: "碧", meaning: "青碧、澄蓝" },
      { char: "空", meaning: "天空" },
    ],
    category: "tangshi",
    source: "李白《黄鹤楼送孟浩然之广陵》",
    dynasty: "唐",
    author: "李白",
    citation: "孤帆远影碧空尽，唯见长江天际流。",
    originalText: "故人西辞黄鹤楼，烟花三月下扬州。孤帆远影碧空尽，唯见长江天际流。",
    interpretation: "孤帆远去的身影消失在碧蓝天空的尽头，只见长江水向天际流去。",
    meaning: "碧蓝长空，寓胸襟澄阔、志向高远、情谊绵长。",
    gender: "male",
    tags: ["澄阔", "高远", "情谊"],
  },
  {
    id: "ts-qinglian",
    name: "青莲",
    chars: [
      { char: "青", meaning: "青色、清净" },
      { char: "莲", meaning: "莲花，出淤泥而不染" },
    ],
    category: "tangshi",
    source: "李白号「青莲居士」",
    dynasty: "唐",
    author: "李白",
    citation: "青莲居士谪仙人，酒肆藏名三十春。",
    originalText: "李白少有才志，隐居于蜀中青莲乡，自号青莲居士，后人才情追慕。",
    interpretation: "李白少隐蜀中青莲乡，自号青莲居士，喻其清净脱俗之志。",
    meaning: "青色莲花，亦李白之号，寓清净高洁、才华超逸、出尘不染。",
    gender: "female",
    tags: ["清净", "高洁", "才情"],
  },
  {
    id: "ts-mingyue",
    name: "明月",
    chars: [
      { char: "明", meaning: "光明、清澈" },
      { char: "月", meaning: "月亮" },
    ],
    category: "tangshi",
    source: "李白《静夜思》",
    dynasty: "唐",
    author: "李白",
    citation: "举头望明月，低头思故乡。",
    originalText: "床前明月光，疑是地上霜。举头望明月，低头思故乡。",
    interpretation: "床前洒满月光，疑是地上秋霜；抬头望明月，低头思念故乡。",
    meaning: "皎洁明月，寓心地光明、思乡念本、皎然不染。",
    gender: "unisex",
    tags: ["光明", "思乡", "皎洁"],
  },
  {
    id: "ts-cangcang",
    name: "苍苍",
    chars: [
      { char: "苍", meaning: "深青色、苍老" },
    ],
    category: "tangshi",
    source: "白居易《赋得古原草送别》",
    dynasty: "唐",
    author: "白居易",
    citation: "离离原上草，一岁一枯荣。",
    originalText: "离离原上草，一岁一枯荣。野火烧不尽，春风吹又生。远芳侵古道，晴翠接荒城。又送王孙去，萋萋满别情。",
    interpretation: "原野上的青草茂盛，一年一度枯萎又繁荣；野火烧不尽它，春风吹来又新生。",
    meaning: "苍翠茂盛之貌，寓生命顽强、生生不息、坚韧不拔。",
    gender: "male",
    tags: ["顽强", "生生不息", "坚韧"],
  },
  {
    id: "ts-wangyue",
    name: "望岳",
    chars: [
      { char: "望", meaning: "仰望、远望" },
      { char: "岳", meaning: "高山、泰山" },
    ],
    category: "tangshi",
    source: "杜甫《望岳》",
    dynasty: "唐",
    author: "杜甫",
    citation: "会当凌绝顶，一览众山小。",
    originalText: "岱宗夫如何？齐鲁青未了。造化钟神秀，阴阳割昏晓。荡胸生曾云，决眦入归鸟。会当凌绝顶，一览众山小。",
    interpretation: "终当登上泰山的最高峰，一览众山的渺小。",
    meaning: "仰望高山、登临绝顶，寓志存高远、勇攀高峰、胸怀天下。",
    gender: "male",
    tags: ["高远", "登顶", "胸怀"],
  },

  // ==================== 宋词（16） ====================
  {
    id: "sc-chanjuan",
    name: "婵娟",
    chars: [
      { char: "婵", meaning: "美好、婵娟" },
      { char: "娟", meaning: "秀丽" },
    ],
    category: "songci",
    source: "苏轼《水调歌头·明月几时有》",
    dynasty: "宋",
    author: "苏轼",
    citation: "但愿人长久，千里共婵娟。",
    originalText: "人有悲欢离合，月有阴晴圆缺，此事古难全。但愿人长久，千里共婵娟。",
    interpretation: "人有悲欢离合，月有阴晴圆缺，自古难全；只愿人们长健久安，纵隔千里也能共赏这美好的月光。",
    meaning: "美好月色亦喻佳人，寓团圆美满、情谊长存、秀美温婉。",
    gender: "female",
    tags: ["团圆", "美好", "温婉"],
  },
  {
    id: "sc-yuyu",
    name: "玉宇",
    chars: [
      { char: "玉", meaning: "美玉、洁白" },
      { char: "宇", meaning: "屋宇、宇宙" },
    ],
    category: "songci",
    source: "苏轼《水调歌头·明月几时有》",
    dynasty: "宋",
    author: "苏轼",
    citation: "我欲乘风归去，又恐琼楼玉宇，高处不胜寒。",
    originalText: "我欲乘风归去，又恐琼楼玉宇，高处不胜寒。起舞弄清影，何似在人间。",
    interpretation: "我想乘风回到天上，又怕那美玉般的楼阁殿宇，高处太过寒冷。",
    meaning: "美玉般的殿宇，寓高洁清雅、气宇轩昂、超凡脱俗。",
    gender: "male",
    tags: ["高洁", "气宇", "超凡"],
  },
  {
    id: "sc-qingfang",
    name: "晴方",
    chars: [
      { char: "晴", meaning: "晴朗" },
      { char: "方", meaning: "正当、恰好" },
    ],
    category: "songci",
    source: "苏轼《饮湖上初晴后雨》",
    dynasty: "宋",
    author: "苏轼",
    citation: "水光潋滟晴方好，山色空蒙雨亦奇。",
    originalText: "水光潋滟晴方好，山色空蒙雨亦奇。欲把西湖比西子，淡妆浓抹总相宜。",
    interpretation: "晴天时水光潋滟正好，雨天时山色空蒙亦奇；若把西湖比作西施，淡妆浓抹总相宜。",
    meaning: "晴光正好，寓明朗开朗、恰到好处、各得其宜。",
    gender: "female",
    tags: ["明朗", "相宜", "开朗"],
  },
  {
    id: "sc-lianyan",
    name: "潋滟",
    chars: [
      { char: "潋", meaning: "水波荡漾" },
      { char: "滟", meaning: "水满溢、波光" },
    ],
    category: "songci",
    source: "苏轼《饮湖上初晴后雨》",
    dynasty: "宋",
    author: "苏轼",
    citation: "水光潋滟晴方好，山色空蒙雨亦奇。",
    originalText: "水光潋滟晴方好，山色空蒙雨亦奇。",
    interpretation: "晴天时水光荡漾正好，雨天时山色空蒙亦奇。",
    meaning: "水光荡漾之貌，寓灵动明丽、光彩照人、丰盈美好。",
    gender: "female",
    tags: ["灵动", "明丽", "丰盈"],
  },
  {
    id: "sc-feihong",
    name: "飞鸿",
    chars: [
      { char: "飞", meaning: "飞翔" },
      { char: "鸿", meaning: "大雁、宏大" },
    ],
    category: "songci",
    source: "苏轼《和子由渑池怀旧》",
    dynasty: "宋",
    author: "苏轼",
    citation: "人生到处知何似，应似飞鸿踏雪泥。",
    originalText: "人生到处知何似，应似飞鸿踏雪泥。泥上偶然留指爪，鸿飞那复计东西。",
    interpretation: "人生所到之处像什么呢？应该像飞雁踏在雪泥之上；偶然留下爪印，雁飞走后哪还顾及东西。",
    meaning: "飞雁踏雪，寓豁达洒脱、志在四方、不留执念。",
    gender: "male",
    tags: ["豁达", "洒脱", "远志"],
  },
  {
    id: "sc-jinghong",
    name: "惊鸿",
    chars: [
      { char: "惊", meaning: "惊起、惊艳" },
      { char: "鸿", meaning: "鸿雁，喻轻盈身姿" },
    ],
    category: "songci",
    source: "陆游《沈园》",
    dynasty: "宋",
    author: "陆游",
    citation: "伤心桥下春波绿，曾是惊鸿照影来。",
    originalText: "城上斜阳画角哀，沈园非复旧池台。伤心桥下春波绿，曾是惊鸿照影来。",
    interpretation: "伤心桥下春水碧绿，当年曾有惊鸿般的倩影倒映水中。",
    meaning: "惊起的鸿雁喻轻盈之美，寓身姿轻盈、美丽动人、令人惊艳。",
    gender: "female",
    tags: ["轻盈", "美丽", "惊艳"],
  },
  {
    id: "sc-chunbo",
    name: "春波",
    chars: [
      { char: "春", meaning: "春天、生机" },
      { char: "波", meaning: "水波" },
    ],
    category: "songci",
    source: "陆游《沈园》",
    dynasty: "宋",
    author: "陆游",
    citation: "伤心桥下春波绿，曾是惊鸿照影来。",
    originalText: "伤心桥下春波绿，曾是惊鸿照影来。",
    interpretation: "伤心桥下春水碧绿，曾有惊鸿般倩影映照而来。",
    meaning: "春日碧波，寓生机盎然、温柔明澈、情深意长。",
    gender: "female",
    tags: ["生机", "温柔", "情深"],
  },
  {
    id: "sc-anxiang",
    name: "暗香",
    chars: [
      { char: "暗", meaning: "幽暗、悄然" },
      { char: "香", meaning: "芳香" },
    ],
    category: "songci",
    source: "林逋《山园小梅》",
    dynasty: "宋",
    author: "林逋",
    citation: "疏影横斜水清浅，暗香浮动月黄昏。",
    originalText: "众芳摇落独暄妍，占尽风情向小园。疏影横斜水清浅，暗香浮动月黄昏。",
    interpretation: "百花凋零唯梅花独美，占尽小园风情；疏朗的梅影横斜在清浅的水上，幽香在月下黄昏浮动。",
    meaning: "梅花幽香，寓品格高洁、含蓄幽雅、不事张扬。",
    gender: "female",
    tags: ["高洁", "幽雅", "含蓄"],
  },
  {
    id: "sc-shuying",
    name: "疏影",
    chars: [
      { char: "疏", meaning: "疏朗" },
      { char: "影", meaning: "身影" },
    ],
    category: "songci",
    source: "林逋《山园小梅》",
    dynasty: "宋",
    author: "林逋",
    citation: "疏影横斜水清浅，暗香浮动月黄昏。",
    originalText: "疏影横斜水清浅，暗香浮动月黄昏。",
    interpretation: "疏朗的梅影横斜在清浅的水上，幽香在月下黄昏浮动。",
    meaning: "疏朗梅影，寓清逸脱俗、风骨高雅、卓然独立。",
    gender: "female",
    tags: ["清逸", "高雅", "独立"],
  },
  {
    id: "sc-jinshu",
    name: "锦书",
    chars: [
      { char: "锦", meaning: "锦绣、华美" },
      { char: "书", meaning: "书信" },
    ],
    category: "songci",
    source: "李清照《一剪梅》",
    dynasty: "宋",
    author: "李清照",
    citation: "云中谁寄锦书来，雁字回时，月满西楼。",
    originalText: "红藕香残玉簟秋。轻解罗裳，独上兰舟。云中谁寄锦书来，雁字回时，月满西楼。",
    interpretation: "云中是谁寄来锦书？大雁归来时，月光洒满西楼。",
    meaning: "华美书信，寓情意深长、才情雅致、相思殷切。",
    gender: "female",
    tags: ["情意", "雅致", "相思"],
  },
  {
    id: "sc-yulu",
    name: "玉露",
    chars: [
      { char: "玉", meaning: "美玉、洁白" },
      { char: "露", meaning: "露水" },
    ],
    category: "songci",
    source: "秦观《鹊桥仙》",
    dynasty: "宋",
    author: "秦观",
    citation: "金风玉露一相逢，便胜却人间无数。",
    originalText: "纤云弄巧，飞星传恨，银汉迢迢暗度。金风玉露一相逢，便胜却人间无数。柔情似水，佳期如梦，忍顾鹊桥归路。",
    interpretation: "秋风白露之际牛郎织女一相逢，便胜过人间无数次相聚。",
    meaning: "秋日白露如玉，寓高洁珍贵、情意深挚、相逢可贵。",
    gender: "female",
    tags: ["高洁", "珍贵", "深情"],
  },
  {
    id: "sc-rouqing",
    name: "柔情",
    chars: [
      { char: "柔", meaning: "温柔" },
      { char: "情", meaning: "情意" },
    ],
    category: "songci",
    source: "秦观《鹊桥仙》",
    dynasty: "宋",
    author: "秦观",
    citation: "柔情似水，佳期如梦。",
    originalText: "柔情似水，佳期如梦，忍顾鹊桥归路。两情若是久长时，又岂在朝朝暮暮。",
    interpretation: "柔情似水绵长，佳期如梦短暂；怎忍回望鹊桥归路？若两情久长，又岂在朝暮相守。",
    meaning: "温柔似水之情，寓性情温润、情意绵长、忠贞不渝。",
    gender: "female",
    tags: ["温柔", "绵长", "忠贞"],
  },
  {
    id: "sc-qingqiu",
    name: "清秋",
    chars: [
      { char: "清", meaning: "清冷、清朗" },
      { char: "秋", meaning: "秋天" },
    ],
    category: "songci",
    source: "李煜《相见欢》",
    dynasty: "南唐",
    author: "李煜",
    citation: "无言独上西楼，月如钩，寂寞梧桐深院锁清秋。",
    originalText: "无言独上西楼，月如钩，寂寞梧桐深院锁清秋。剪不断，理还乱，是离愁，别是一般滋味在心头。",
    interpretation: "默默独自登上西楼，月如弯钩，寂寞的梧桐深院锁住了清冷的秋意。",
    meaning: "清冷秋意，寓气质清朗、心境澄明、超然淡远。",
    gender: "unisex",
    tags: ["清朗", "澄明", "淡远"],
  },
  {
    id: "sc-gouyue",
    name: "钩月",
    chars: [
      { char: "钩", meaning: "弯钩" },
      { char: "月", meaning: "月亮" },
    ],
    category: "songci",
    source: "李煜《相见欢》",
    dynasty: "南唐",
    author: "李煜",
    citation: "无言独上西楼，月如钩。",
    originalText: "无言独上西楼，月如钩，寂寞梧桐深院锁清秋。",
    interpretation: "默默独自登上西楼，月亮弯如银钩。",
    meaning: "弯如银钩之月，寓清雅含蓄、皎洁幽远、独具风致。",
    gender: "female",
    tags: ["清雅", "皎洁", "幽远"],
  },
  {
    id: "sc-dongfeng",
    name: "东风",
    chars: [
      { char: "东", meaning: "东方、春" },
      { char: "风", meaning: "风、春风" },
    ],
    category: "songci",
    source: "李煜《虞美人》",
    dynasty: "南唐",
    author: "李煜",
    citation: "小楼昨夜又东风，故国不堪回首月明中。",
    originalText: "春花秋月何时了，往事知多少。小楼昨夜又东风，故国不堪回首月明中。",
    interpretation: "昨夜小楼又吹起东风，明月之中故国不堪回首。",
    meaning: "春风自东方来，寓带来生机、和煦温暖、承续更迭。",
    gender: "male",
    tags: ["生机", "和煦", "更迭"],
  },
  {
    id: "sc-chunhua",
    name: "春花",
    chars: [
      { char: "春", meaning: "春天" },
      { char: "花", meaning: "花朵" },
    ],
    category: "songci",
    source: "李煜《虞美人》",
    dynasty: "南唐",
    author: "李煜",
    citation: "春花秋月何时了，往事知多少。",
    originalText: "春花秋月何时了，往事知多少。小楼昨夜又东风，故国不堪回首月明中。",
    interpretation: "春花秋月何时才能了结，往事又知多少。",
    meaning: "春日繁花，寓美好灿烂、年华似锦、生机盎然。",
    gender: "female",
    tags: ["美好", "灿烂", "盎然"],
  },

  // ==================== 四书（论学庸孟）（14） ====================
  {
    id: "ss-zhishan",
    name: "至善",
    chars: [
      { char: "至", meaning: "极、最" },
      { char: "善", meaning: "善、美好" },
    ],
    category: "sishu",
    source: "《大学》",
    dynasty: "先秦",
    author: "曾子",
    citation: "大学之道，在明明德，在亲民，在止于至善。",
    originalText: "大学之道，在明明德，在亲民，在止于至善。知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。",
    interpretation: "大学的宗旨，在于彰明美德，在于亲爱民众，在于达到并保持最完善的境界。",
    meaning: "达到最完善之境，寓追求卓越、止于至美、德行圆满。",
    gender: "unisex",
    tags: ["至善", "卓越", "圆满"],
  },
  {
    id: "ss-mingde",
    name: "明德",
    chars: [
      { char: "明", meaning: "彰明、光明" },
      { char: "德", meaning: "美德" },
    ],
    category: "sishu",
    source: "《大学》",
    dynasty: "先秦",
    author: "曾子",
    citation: "大学之道，在明明德。",
    originalText: "大学之道，在明明德，在亲民，在止于至善。",
    interpretation: "大学的宗旨，在于彰明人与生俱来的光明德性。",
    meaning: "彰明美德，寓德行光明、修身立本、德化于人。",
    gender: "male",
    tags: ["美德", "修身", "光明"],
  },
  {
    id: "ss-runshen",
    name: "润身",
    chars: [
      { char: "润", meaning: "滋润、润泽" },
      { char: "身", meaning: "自身、身心" },
    ],
    category: "sishu",
    source: "《大学》",
    dynasty: "先秦",
    author: "曾子",
    citation: "富润屋，德润身，心广体胖。",
    originalText: "富润屋，德润身，心广体胖，故君子必诚其意。",
    interpretation: "财富能润饰屋宇，美德能润泽身心，心胸宽广体态舒泰，故君子必诚其意。",
    meaning: "美德润泽身心，寓以德养身、内外兼修、心安体泰。",
    gender: "male",
    tags: ["美德", "修身", "心安"],
  },
  {
    id: "ss-shendu",
    name: "慎独",
    chars: [
      { char: "慎", meaning: "谨慎" },
      { char: "独", meaning: "独处" },
    ],
    category: "sishu",
    source: "《大学》",
    dynasty: "先秦",
    author: "曾子",
    citation: "故君子必慎其独也。",
    originalText: "所谓诚其意者，毋自欺也。……故君子必慎其独也。",
    interpretation: "所谓诚意，就是不自我欺骗；所以君子在独处时必定谨慎守德。",
    meaning: "独处时亦谨慎守德，寓自律严谨、表里如一、德操坚定。",
    gender: "male",
    tags: ["自律", "严谨", "守德"],
  },
  {
    id: "ss-duhang",
    name: "笃行",
    chars: [
      { char: "笃", meaning: "切实、专心" },
      { char: "行", meaning: "践行" },
    ],
    category: "sishu",
    source: "《中庸》",
    dynasty: "先秦",
    author: "子思",
    citation: "博学之，审问之，慎思之，明辨之，笃行之。",
    originalText: "博学之，审问之，慎思之，明辨之，笃行之。有弗学，学之弗能弗措也。",
    interpretation: "广博地学习，审慎地询问，慎重地思考，明晰地辨别，切实地践行。",
    meaning: "切实地践行，寓知行合一、脚踏实地、持之以恒。",
    gender: "male",
    tags: ["践行", "知行合一", "踏实"],
  },
  {
    id: "ss-mingbian",
    name: "明辨",
    chars: [
      { char: "明", meaning: "明晰" },
      { char: "辨", meaning: "辨别" },
    ],
    category: "sishu",
    source: "《中庸》",
    dynasty: "先秦",
    author: "子思",
    citation: "博学之，审问之，慎思之，明辨之，笃行之。",
    originalText: "博学之，审问之，慎思之，明辨之，笃行之。",
    interpretation: "广博学习，审慎询问，慎重思考，明晰辨别，切实践行。",
    meaning: "明晰地辨别是非，寓头脑清明、判别精当、不惑于世。",
    gender: "male",
    tags: ["清明", "辨别", "不惑"],
  },
  {
    id: "ss-zhonghe",
    name: "中和",
    chars: [
      { char: "中", meaning: "中正、不偏" },
      { char: "和", meaning: "和谐、和顺" },
    ],
    category: "sishu",
    source: "《中庸》",
    dynasty: "先秦",
    author: "子思",
    citation: "致中和，天地位焉，万物育焉。",
    originalText: "喜怒哀乐之未发，谓之中；发而皆中节，谓之和。中也者，天下之大本也；和也者，天下之达道也。致中和，天地位焉，万物育焉。",
    interpretation: "情未发谓之中，发而合度谓之和；达到中和，天地各得其位，万物生长育化。",
    meaning: "中正和谐，寓性情中和、不偏不倚、万事顺遂。",
    gender: "unisex",
    tags: ["中正", "和谐", "顺遂"],
  },
  {
    id: "ss-hongyi",
    name: "弘毅",
    chars: [
      { char: "弘", meaning: "广大" },
      { char: "毅", meaning: "坚毅" },
    ],
    category: "sishu",
    source: "《论语·泰伯》",
    dynasty: "春秋",
    author: "曾子",
    citation: "士不可以不弘毅，任重而道远。",
    originalText: "曾子曰：士不可以不弘毅，任重而道远。仁以为己任，不亦重乎？死而后已，不亦远乎？",
    interpretation: "曾子说：士人不可不弘大坚毅，因为责任重大道路遥远；以仁为己任，不重吗？到死方休，不远吗？",
    meaning: "弘大坚毅，寓胸怀宽广、意志坚强、担当重任。",
    gender: "male",
    tags: ["坚毅", "担当", "宽弘"],
  },
  {
    id: "ss-minhang",
    name: "敏行",
    chars: [
      { char: "敏", meaning: "勤敏、敏捷" },
      { char: "行", meaning: "行事" },
    ],
    category: "sishu",
    source: "《论语·里仁》",
    dynasty: "春秋",
    author: "孔子",
    citation: "君子欲讷于言而敏于行。",
    originalText: "子曰：君子欲讷于言而敏于行。",
    interpretation: "孔子说：君子应说话谨慎而行动敏捷。",
    meaning: "勤敏于行，寓言行务实、勤勉果决、不尚空谈。",
    gender: "male",
    tags: ["勤敏", "务实", "果决"],
  },
  {
    id: "ss-leshan",
    name: "乐山",
    chars: [
      { char: "乐", meaning: "喜爱、乐于" },
      { char: "山", meaning: "山，喻稳重" },
    ],
    category: "sishu",
    source: "《论语·雍也》",
    dynasty: "春秋",
    author: "孔子",
    citation: "知者乐水，仁者乐山。",
    originalText: "子曰：知者乐水，仁者乐山；知者动，仁者静；知者乐，仁者寿。",
    interpretation: "孔子说：智者喜爱水，仁者喜爱山；智者动，仁者静；智者乐，仁者寿。",
    meaning: "仁者乐山，寓仁厚如山、稳重沉静、福寿绵长。",
    gender: "male",
    tags: ["仁厚", "稳重", "福寿"],
  },
  {
    id: "ss-leshui",
    name: "乐水",
    chars: [
      { char: "乐", meaning: "喜爱" },
      { char: "水", meaning: "水，喻灵动" },
    ],
    category: "sishu",
    source: "《论语·雍也》",
    dynasty: "春秋",
    author: "孔子",
    citation: "知者乐水，仁者乐山。",
    originalText: "子曰：知者乐水，仁者乐山；知者动，仁者静；知者乐，仁者寿。",
    interpretation: "智者喜爱水，仁者喜爱山；智者动，仁者静；智者乐，仁者寿。",
    meaning: "智者乐水，寓智慧灵动、通达应变、乐而无忧。",
    gender: "unisex",
    tags: ["智慧", "灵动", "通达"],
  },
  {
    id: "ss-haoran",
    name: "浩然",
    chars: [
      { char: "浩", meaning: "盛大" },
      { char: "然", meaning: "……的样子" },
    ],
    category: "sishu",
    source: "《孟子·公孙丑上》",
    dynasty: "战国",
    author: "孟子",
    citation: "我善养吾浩然之气。",
    originalText: "我知言，我善养吾浩然之气。……其为气也，至大至刚，以直养而无害，则塞于天地之间。",
    interpretation: "我善于培养我的浩然之气；这种气至大至刚，以正义培养便充塞天地之间。",
    meaning: "浩然正气，寓光明磊落、刚正不阿、气贯长虹。",
    gender: "male",
    tags: ["正气", "刚正", "磊落"],
  },
  {
    id: "ss-jiyi",
    name: "集义",
    chars: [
      { char: "集", meaning: "聚集、积累" },
      { char: "义", meaning: "正义、道义" },
    ],
    category: "sishu",
    source: "《孟子·公孙丑上》",
    dynasty: "战国",
    author: "孟子",
    citation: "是集义所生者，非义袭而取之也。",
    originalText: "其为气也，配义与道；无是，馁也。是集义所生者，非义袭而取之也。",
    interpretation: "这种浩然之气，须与义与道相配；它是不断积累正义所生，非偶然行义可得。",
    meaning: "积累正义，寓日积月善、行义不止、德厚流光。",
    gender: "male",
    tags: ["积善", "行义", "德厚"],
  },
  {
    id: "ss-chicheng",
    name: "赤诚",
    chars: [
      { char: "赤", meaning: "赤色、纯真" },
      { char: "诚", meaning: "真诚" },
    ],
    category: "sishu",
    source: "《中庸》",
    dynasty: "先秦",
    author: "子思",
    citation: "唯天下至诚，为能尽其性。",
    originalText: "唯天下至诚，为能尽其性；能尽其性，则能尽人之性；能尽人之性，则能尽物之性。",
    interpretation: "唯有天下至诚之人，才能充分发挥自己的本性，进而发挥众人、万物的本性。",
    meaning: "赤子之诚，寓真心至诚、纯粹无伪、达于至性。",
    gender: "male",
    tags: ["真诚", "纯粹", "至性"],
  },

  // ==================== 道德经 / 庄子 / 易经（13） ====================
  {
    id: "dj-ruoshui",
    name: "若水",
    chars: [
      { char: "若", meaning: "如、像" },
      { char: "水", meaning: "水" },
    ],
    category: "daojing",
    source: "《道德经·第八章》",
    dynasty: "春秋",
    author: "老子",
    citation: "上善若水。水善利万物而不争。",
    originalText: "上善若水。水善利万物而不争，处众人之所恶，故几于道。",
    interpretation: "最高的善就像水：水善于滋润万物却不与之争，居于众人所厌恶的低下之处，所以最接近道。",
    meaning: "至善如水，寓柔顺谦下、利物不争、近于大道。",
    gender: "unisex",
    tags: ["柔顺", "谦下", "不争"],
  },
  {
    id: "dj-shanyuan",
    name: "善渊",
    chars: [
      { char: "善", meaning: "善于" },
      { char: "渊", meaning: "深、沉静" },
    ],
    category: "daojing",
    source: "《道德经·第八章》",
    dynasty: "春秋",
    author: "老子",
    citation: "心善渊，与善仁。",
    originalText: "居善地，心善渊，与善仁，言善信，正善治，事善能，动善时。",
    interpretation: "居处善于择地，心胸善于沉静如渊，交往善于仁爱，言语善于守信。",
    meaning: "心善如渊之深沉，寓心境深邃、沉稳内敛、涵养深厚。",
    gender: "male",
    tags: ["深邃", "沉稳", "涵养"],
  },
  {
    id: "dj-xisheng",
    name: "希声",
    chars: [
      { char: "希", meaning: "稀少、无声" },
      { char: "声", meaning: "声音" },
    ],
    category: "daojing",
    source: "《道德经·第四十一章》",
    dynasty: "春秋",
    author: "老子",
    citation: "大音希声，大象无形。",
    originalText: "明道若昧，进道若退，夷道若颣。上德若谷，大白若辱，广德若不足。大音希声，大象无形，道隐无名。",
    interpretation: "光明的道看似暗昧，前进的道看似后退；最美的声音少有声响，最大的形象没有形迹。",
    meaning: "大音稀声，寓含蓄内敛、大美不言、深藏若虚。",
    gender: "male",
    tags: ["含蓄", "内敛", "大美"],
  },
  {
    id: "dj-weiming",
    name: "微明",
    chars: [
      { char: "微", meaning: "幽微、精妙" },
      { char: "明", meaning: "光明、明智" },
    ],
    category: "daojing",
    source: "《道德经·第三十六章》",
    dynasty: "春秋",
    author: "老子",
    citation: "是谓微明。",
    originalText: "将欲歙之，必固张之；将欲弱之，必固强之；将欲废之，必固兴之；将欲取之，必固与之。是谓微明。",
    interpretation: "将要收敛它，必先扩张它；将要削弱它，必先强化它……这叫做幽微的明智。",
    meaning: "幽微之明，寓洞察幽微、智而不露、明察机先。",
    gender: "unisex",
    tags: ["幽微", "洞察", "明智"],
  },
  {
    id: "dj-baoyi",
    name: "抱一",
    chars: [
      { char: "抱", meaning: "持守" },
      { char: "一", meaning: "道、本原" },
    ],
    category: "daojing",
    source: "《道德经·第二十二章》",
    dynasty: "春秋",
    author: "老子",
    citation: "是以圣人抱一为天下式。",
    originalText: "曲则全，枉则直，洼则盈，敝则新，少则得，多则惑。是以圣人抱一为天下式。",
    interpretation: "委曲反能保全，弯枉反能伸直；所以圣人持守大道之一，作为天下的法式。",
    meaning: "持守大道本原，寓专一守道、不纷不乱、为世楷模。",
    gender: "male",
    tags: ["守一", "专一", "楷模"],
  },
  {
    id: "dj-guangchen",
    name: "光尘",
    chars: [
      { char: "光", meaning: "光华" },
      { char: "尘", meaning: "尘世" },
    ],
    category: "daojing",
    source: "《道德经·第五十六章》",
    dynasty: "春秋",
    author: "老子",
    citation: "和其光，同其尘，是谓玄同。",
    originalText: "知者不言，言者不知。塞其兑，闭其门，挫其锐，解其纷，和其光，同其尘，是谓玄同。",
    interpretation: "智者不多言，多言者不知；收敛锋芒、化解纷扰、和光同尘，这叫做玄妙的同一。",
    meaning: "和光同尘，寓韬光养晦、与世无争、深藏不露。",
    gender: "male",
    tags: ["韬光", "养晦", "不争"],
  },
  {
    id: "dj-fuyao",
    name: "扶摇",
    chars: [
      { char: "扶", meaning: "扶摇、盘旋而上" },
      { char: "摇", meaning: "摇动、上升" },
    ],
    category: "daojing",
    source: "《庄子·逍遥游》",
    dynasty: "战国",
    author: "庄子",
    citation: "鹏之徙于南冥也，水击三千里，抟扶摇而上者九万里。",
    originalText: "鹏之徙于南冥也，水击三千里，抟扶摇而上者九万里，去以六月息者也。",
    interpretation: "大鹏迁往南海时，翅膀击水三千里，乘着旋风盘旋而上九万里。",
    meaning: "盘旋而上的旋风，寓乘势而上、志在九万、扶摇万里。",
    gender: "male",
    tags: ["乘势", "高远", "鹏程"],
  },
  {
    id: "dj-xiaoyao",
    name: "逍遥",
    chars: [
      { char: "逍", meaning: "逍遥、自由" },
      { char: "遥", meaning: "遥远、自在" },
    ],
    category: "daojing",
    source: "《庄子·逍遥游》",
    dynasty: "战国",
    author: "庄子",
    citation: "彷徨乎尘垢之外，逍遥乎无为之业。",
    originalText: "今子有大树，患其无用，何不树之于无何有之乡，广莫之野，彷徨乎无为其侧，逍遥乎寝卧其下。",
    interpretation: "如今你有这大树，愁它无用，何不种在无何有之乡、广漠之野，彷徨于其侧，逍遥卧于其下。",
    meaning: "自由自在、无拘无束，寓心境旷达、超然物外、自在逍遥。",
    gender: "unisex",
    tags: ["自在", "旷达", "超然"],
  },
  {
    id: "dj-zhiyu",
    name: "知鱼",
    chars: [
      { char: "知", meaning: "知晓" },
      { char: "鱼", meaning: "鱼" },
    ],
    category: "daojing",
    source: "《庄子·秋水》",
    dynasty: "战国",
    author: "庄子",
    citation: "子非鱼，安知鱼之乐？",
    originalText: "庄子与惠子游于濠梁之上。庄子曰：鯈鱼出游从容，是鱼之乐也。惠子曰：子非鱼，安知鱼之乐？",
    interpretation: "庄子说鱼出游从容是鱼之乐，惠子问：你不是鱼，怎么知道鱼的快乐？",
    meaning: "知鱼之乐，寓体物入微、自得其乐、心境悠然。",
    gender: "unisex",
    tags: ["体物", "自得", "悠然"],
  },
  {
    id: "dj-qianyuan",
    name: "乾元",
    chars: [
      { char: "乾", meaning: "天、刚健" },
      { char: "元", meaning: "始、本原" },
    ],
    category: "daojing",
    source: "《易经·乾卦》",
    dynasty: "先秦",
    author: "周文王/周公",
    citation: "大哉乾元，万物资始，乃统天。",
    originalText: "大哉乾元，万物资始，乃统天。云行雨施，品物流形。大明终始，六位时成，时乘六龙以御天。",
    interpretation: "伟大啊天的本元，万物赖以开始，统领整个天道。",
    meaning: "天道之本元，寓刚健有为、开创万物、统御之才。",
    gender: "male",
    tags: ["刚健", "开创", "统御"],
  },
  {
    id: "dj-yuanheng",
    name: "元亨",
    chars: [
      { char: "元", meaning: "大、始" },
      { char: "亨", meaning: "通达、顺利" },
    ],
    category: "daojing",
    source: "《易经·乾卦》",
    dynasty: "先秦",
    author: "周文王/周公",
    citation: "乾，元亨利贞。",
    originalText: "乾，元亨利贞。",
    interpretation: "乾卦：大、通、利、正，万物始生而通达。",
    meaning: "大通大利，寓开创亨通、顺遂有成、正道而行。",
    gender: "male",
    tags: ["亨通", "顺遂", "正道"],
  },
  {
    id: "dj-hanzhang",
    name: "含章",
    chars: [
      { char: "含", meaning: "含藏" },
      { char: "章", meaning: "文采、美德" },
    ],
    category: "daojing",
    source: "《易经·坤卦》",
    dynasty: "先秦",
    author: "周文王/周公",
    citation: "六三：含章可贞。或从王事，无成有终。",
    originalText: "六三：含章可贞。或从王事，无成有终。",
    interpretation: "六三：含藏美才可守正道；若从事王事，不居功亦能有善终。",
    meaning: "含藏文采美德，寓内秀不炫、守正不伐、终有善果。",
    gender: "female",
    tags: ["内秀", "守正", "不伐"],
  },
  {
    id: "dj-qianjie",
    name: "谦光",
    chars: [
      { char: "谦", meaning: "谦虚" },
      { char: "光", meaning: "光耀" },
    ],
    category: "daojing",
    source: "《易经·谦卦》",
    dynasty: "先秦",
    author: "周文王/周公",
    citation: "谦尊而光，卑而不可逾，君子之终也。",
    originalText: "谦尊而光，卑而不可逾，君子之终也。",
    interpretation: "谦逊者位居尊而更显光耀，处卑下却不可逾越，这是君子的归宿。",
    meaning: "谦而光耀，寓谦虚有德、光而不耀、终成君子。",
    gender: "male",
    tags: ["谦虚", "光耀", "君子"],
  },

  // ==================== 尚书 / 礼记 / 其他典籍（8） ====================
  {
    id: "dj-xiehe",
    name: "协和",
    chars: [
      { char: "协", meaning: "协同、和睦" },
      { char: "和", meaning: "和平、和谐" },
    ],
    category: "dianji",
    source: "《尚书·尧典》",
    dynasty: "上古",
    author: "佚名",
    citation: "克明俊德，以亲九族。九族既睦，平章百姓。百姓昭明，协和万邦。",
    originalText: "克明俊德，以亲九族。九族既睦，平章百姓。百姓昭明，协和万邦。",
    interpretation: "能明大德以亲睦九族；九族既和睦，便彰明百官；百官昭明，便协和天下万邦。",
    meaning: "协和万邦，寓和合天下、胸怀苍生、德化四方。",
    gender: "male",
    tags: ["和谐", "胸怀", "德化"],
  },
  {
    id: "dj-junde",
    name: "俊德",
    chars: [
      { char: "俊", meaning: "大、杰出" },
      { char: "德", meaning: "美德" },
    ],
    category: "dianji",
    source: "《尚书·尧典》",
    dynasty: "上古",
    author: "佚名",
    citation: "克明俊德，以亲九族。",
    originalText: "克明俊德，以亲九族。九族既睦，平章百姓。",
    interpretation: "能彰明大德，以此亲睦九族。",
    meaning: "大德杰出，寓德才出众、明德修身、泽被亲族。",
    gender: "male",
    tags: ["大德", "杰出", "修身"],
  },
  {
    id: "dj-weixin",
    name: "惟馨",
    chars: [
      { char: "惟", meaning: "只、是" },
      { char: "馨", meaning: "芳香远闻" },
    ],
    category: "dianji",
    source: "《尚书·君陈》",
    dynasty: "上古",
    author: "佚名",
    citation: "黍稷非馨，明德惟馨。",
    originalText: "至治馨香，感于神明。黍稷非馨，明德惟馨。",
    interpretation: "太平之治的馨香上达神明；五谷并非真正馨香，唯有美德才是馨香。",
    meaning: "惟有美德馨香，寓德香远播、芳名长存、以德立身。",
    gender: "female",
    tags: ["美德", "芳名", "德香"],
  },
  {
    id: "dj-mingde2",
    name: "明馨",
    chars: [
      { char: "明", meaning: "光明、彰明" },
      { char: "馨", meaning: "芳香" },
    ],
    category: "dianji",
    source: "《尚书·君陈》",
    dynasty: "上古",
    author: "佚名",
    citation: "黍稷非馨，明德惟馨。",
    originalText: "黍稷非馨，明德惟馨。",
    interpretation: "五谷并非真正馨香，唯有彰明的美德才是馨香。",
    meaning: "明德之馨香，寓德行芳洁、光明远播、声名美善。",
    gender: "female",
    tags: ["德行", "芳洁", "美名"],
  },
  {
    id: "dj-zhonghe",
    name: "致和",
    chars: [
      { char: "致", meaning: "达到、尽心" },
      { char: "和", meaning: "和谐" },
    ],
    category: "dianji",
    source: "《礼记·中庸》",
    dynasty: "先秦",
    author: "子思",
    citation: "致中和，天地位焉，万物育焉。",
    originalText: "致中和，天地位焉，万物育焉。",
    interpretation: "达到中和之境，天地各安其位，万物得以生育。",
    meaning: "致力于中和，寓和顺达致、尽心谐和、万物各得其所。",
    gender: "unisex",
    tags: ["和谐", "尽心", "和顺"],
  },
  {
    id: "dj-daya",
    name: "大雅",
    chars: [
      { char: "大", meaning: "大、正" },
      { char: "雅", meaning: "雅正、高尚" },
    ],
    category: "dianji",
    source: "《诗经·大雅》",
    dynasty: "西周",
    author: "佚名",
    citation: "大雅久不作，吾衰竟谁陈。",
    originalText: "《大雅》为诗经正声，言王政之所由废兴。",
    interpretation: "《大雅》是《诗经》正声，记述王政兴废之源。",
    meaning: "雅正大方，寓气质高雅、正大光明、卓尔不凡。",
    gender: "unisex",
    tags: ["高雅", "正大", "不凡"],
  },
  {
    id: "dj-zhishu",
    name: "致书",
    chars: [
      { char: "致", meaning: "致力于" },
      { char: "书", meaning: "读书、学问" },
    ],
    category: "dianji",
    source: "《礼记·学记》",
    dynasty: "先秦",
    author: "佚名",
    citation: "玉不琢，不成器；人不学，不知道。",
    originalText: "玉不琢，不成器；人不学，不知道。是故古之王者建国君民，教学为先。",
    interpretation: "玉石不经雕琢不能成器，人不学习不能明道；故古之王者立国治民，以教学为先。",
    meaning: "致力于学问之道，寓勤学明道、玉琢成器、修身立业。",
    gender: "male",
    tags: ["勤学", "明道", "修身"],
  },
  {
    id: "dj-zhiyuan",
    name: "致远",
    chars: [
      { char: "致", meaning: "达到" },
      { char: "远", meaning: "远方、深远" },
    ],
    category: "dianji",
    source: "诸葛亮《诫子书》",
    dynasty: "三国",
    author: "诸葛亮",
    citation: "非淡泊无以明志，非宁静无以致远。",
    originalText: "夫君子之行，静以修身，俭以养德。非淡泊无以明志，非宁静无以致远。夫学须静也，才须学也。",
    interpretation: "君子之行，以静修身以俭养德；不淡泊不能明志，不宁静不能致远。",
    meaning: "宁静方能致远，寓心境淡泊、志存高远、行稳致远。",
    gender: "male",
    tags: ["淡泊", "高远", "宁静"],
  },
];

// ==================== 工具函数 ====================
export function getCardsByCategory(category: string): NameCard[] {
  return NAME_CARDS.filter((c) => c.category === category);
}

export function getCardsByGender(gender: string): NameCard[] {
  if (gender === "all") return NAME_CARDS;
  return NAME_CARDS.filter(
    (c) => c.gender === gender || c.gender === "unisex",
  );
}

export function getCardById(id: string): NameCard | undefined {
  return NAME_CARDS.find((c) => c.id === id);
}

export function getAllTags(): string[] {
  const set = new Set<string>();
  NAME_CARDS.forEach((c) => c.tags.forEach((t) => set.add(t)));
  return Array.from(set).sort();
}

export const TOTAL_COUNT = NAME_CARDS.length;
